package com.binance.api.client.domain.account.request;

import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.builder.ToStringBuilder;

import com.binance.api.client.constant.BinanceApiConstants;

@Setter
@Getter
public class CancelOrderListRequest {

    private String symbol;

    private Long orderListId;

    private String listClientOrderId;

    /**
     * Used to uniquely identify this cancel. Automatically generated by default
     */
    private String newClientOrderId;

    private Long recvWindow;

    private Long timestamp;

    public CancelOrderListRequest(String symbol) {
        this.symbol = symbol;
        this.timestamp = System.currentTimeMillis();
        this.recvWindow = BinanceApiConstants.DEFAULT_RECEIVING_WINDOW;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, BinanceApiConstants.TO_STRING_BUILDER_STYLE).append("symbol", symbol).append("orderListId", orderListId).append("listClientOrderId", listClientOrderId).append("newClientOrderId", newClientOrderId).append("recvWindow", recvWindow).append("timestamp", timestamp).toString();
    }

}